
#+TITLE: bot_269使用說明
#+AUTHOR: CToID(269)
#+OPTIONS: \n:t

*預設前綴為a269(欸, 269), 某些伺服器可能有修改過前綴，可以使用( ~PREFIX~ )來查詢。*
*說明書中有and符號請忽略，這些是用來做分隔之用，指令中不會有這些符號。*

請使用 ~a269 help <目錄中的數字(如1, 2, 3等)>~ 來看更詳細的說明。
直接在聊天室中輸入 ~COPYRIGHT~ 或 ~LICENSE~ 來查看版權聲明和授權條款。
原始碼可以在 https://github.com/funk443/bot_269 找到。

有任何問題也可以連絡我(雖然我也不一定知道怎麼解決就是了):
- Discord: ID#2120
- e-mail: funk443@tutanota.com
- 巴哈: CToID(funk443)

copyright (C) 2022 CToID

&


* 幫助指令(help)
- 幫助目錄
  用法: ~a269 help~

  召喚說明書的目錄。

- 詳細說明
  用法: ~a269 help <目錄中的數字(1, 2, 3等)>~
  &
* 前綴字(prefix)
- 查詢目前前綴字(PREFIX)
  用法: ~PREFIX~

  如題，只要輸入 ~PREFIX~ 就好了，不用加任何前綴字。 

- 更改前綴字(change_prefix)
  用法: ~a269 change_prefix <要改成什麼前綴字>~
  可以將機器人在這個伺服器的前綴字更改成你想要的字串。
  *建議把想更改的前綴字用雙引號(")包起來，以免空白被吃*
  *後面要空格要自己加喔*
  *如果要更改的內容為空，機器人會改回預設前綴字(​a269 )*  
  &
* 伺服器設定用指令(svr_conf)
*只有伺服器擁有者或管理員可用*

- 查看目前設定值
  用法: ~a269 svr_conf~

- 增加管理員
  用法: ~a269 svr_conf + admin <@使用者>~

- 刪除管理員
  用法: ~a269 svr_conf - admin <@使用者>~

- 管理員是否能再增加/刪除管理員
  用法: ~a269 svr_conf set allow_add_by_admin true/false~
  & 
* 按表情符號來取得身份組指令(role_select)
*只有伺服器擁有者或管理員可用*

用法: ~a269 role_select "<訊息內容>" "<表情符號1>/<@身份組1>, <@身份組2>, ...." "<表情符號2>/<@身份組1>, <@身份組2>, ..." ...~

*雙引號(")跟斜線(/)都要記得照上面的格式輸入*
在哪個頻道輸入這個指令，他訊息就會傳到那個頻道。
&
* 回覆指令(reply)
- 新增/修改回覆(add)
  用法1: ~a269 reply add <觸發關鍵字> <回覆內容>~
  用法2: ~a269 reply add <觸發關鍵字>~
    
  用來新增想要的回覆，如果關鍵字已存在則修改該關鍵字的回覆內容。
  如果回覆內容或關鍵字有含空格，應以雙引號(")包起來。
  用法2可以附加多張圖片來讓機器人回覆圖片。  

- 刪除回覆(del)
  用法: ~a269 reply del <觸發關鍵字>~ 
  
  用來刪除在資料庫中的回覆。  

- 尋找關鍵字(findk)
  用法: ~a269 reply findk <回覆內容>~ 
  
  用回覆來反查關鍵字。  

- 尋找回覆(findv)
  用法: ~a269 reply findv <觸發關鍵字>~ 
  
  用關鍵字來找回覆。  

- 列出所有關鍵字列表(list)
  用法: ~a269 reply list~  
  &
* 回應指令(react)
- 新增/修改回應(add)
  用法: ~a269 react add <觸發關鍵字> <要回應的表符1> <要回應的表符2>...(表符間可以用空格格開，也可以不用)~
    
  用來新增想要的回應，如果關鍵字已存在則修改該關鍵字的回應表符。 
  
- 刪除回覆(del)
  用法: ~a269 reply del <觸發關鍵字>~ 
    
  用來刪除在資料庫中的回應。  

- 尋找關鍵字(findk)
  用法: ~a269 reply findk <回應表符>~ 
  
  用回應來反查關鍵字。  

- 尋找回覆(findv)
  用法: ~a269 reply findv <觸發關鍵字>~ 
  
  用關鍵字來找回應。  

- 列出所有關鍵字列表(list)
  用法: ~a269 reply list~  
  &
* 吃什麼指令
- 從預設清單中挑食物
用法: ~a269 吃什麼~ 

- 新增食物到預設清單(add)
用法: ~a269 吃什麼 add <食物1> <食物2>....(食物間以空白隔開)~ 

- 將食物從預設清單中移除(del)
用法: ~a269 吃什麼 del <食物1> <食物2>....(食物間以空白隔開)~

- 將預設清單清空(clr)
用法: ~a269 吃什麼 clr~

- 查看預設清單(list)
用法: ~a269 吃什麼 list~

- 不使用預設清單挑選食物
用法: ~a269 吃什麼 <食物1> <食物2>....(食物間以空白隔開)~
&
* 今日運勢指令
用法: ~a269 今日運勢~

讓機器人告訴你你今天運氣怎麼樣。一天只能用一次。
用超過一次的話機器人會罵你喔。 
&
